// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV0s9TUdit-BK_OuUf_XFOWWsLndkRE78',
    appId: '1:973250361880:web:92967742bf9b06ebf2616d',
    messagingSenderId: '973250361880',
    projectId: 'pitontracker',
    authDomain: 'pitontracker.firebaseapp.com',
    storageBucket: 'pitontracker.firebasestorage.app',
    measurementId: 'G-0YCS00T60P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZDGp6l6kBm9BwO1TxFkRKn02dvJHBgfA',
    appId: '1:973250361880:android:9be55ebd71b803e8f2616d',
    messagingSenderId: '973250361880',
    projectId: 'pitontracker',
    storageBucket: 'pitontracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqGhiFx14tcEEQdpDdOY0y-4DzQdN-YYM',
    appId: '1:973250361880:ios:b0979898b91649adf2616d',
    messagingSenderId: '973250361880',
    projectId: 'pitontracker',
    storageBucket: 'pitontracker.firebasestorage.app',
    iosBundleId: 'com.example.pitonTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqGhiFx14tcEEQdpDdOY0y-4DzQdN-YYM',
    appId: '1:973250361880:ios:b0979898b91649adf2616d',
    messagingSenderId: '973250361880',
    projectId: 'pitontracker',
    storageBucket: 'pitontracker.firebasestorage.app',
    iosBundleId: 'com.example.pitonTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV0s9TUdit-BK_OuUf_XFOWWsLndkRE78',
    appId: '1:973250361880:web:0cfcb8b601b5712cf2616d',
    messagingSenderId: '973250361880',
    projectId: 'pitontracker',
    authDomain: 'pitontracker.firebaseapp.com',
    storageBucket: 'pitontracker.firebasestorage.app',
    measurementId: 'G-E5C4KTJ1TR',
  );
}
