name: Flutter Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v3

      - name: Java Kurulumu
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Paketleri İndir
        run: flutter pub get

      - name: APK Derle
        run: flutter build apk --release