name: Flutter Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v4 # v4'e güncellendi

      - name: Java Kurulumu
        uses: actions/setup-java@v4 # v4'e güncellendi
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Paketleri İndir
        run: flutter pub get

      - name: Kod Analizi (Linting)
        run: flutter analyze

      - name: APK Derle
        run: flutter build apk --release

      - name: Firebase App Distribution'a Gönder
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk